name: safety_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^7.0.0 # ‚Üê added from old branch
  shared_preferences: ^2.5.4
  lottie: ^3.3.2
  dio: ^5.9.0
  http: ^1.6.0
  flutter_secure_storage: ^10.0.0
  go_router: ^17.0.1
  flutter_riverpod: ^3.2.0
  sensors_plus: ^6.1.0
  qr_flutter: ^4.1.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.3.1
  permission_handler: ^12.0.1
  mobile_scanner: ^7.1.4
  image_picker: ^1.2.1
  google_mlkit_barcode_scanning: ^0.14.1
  share_plus: ^12.0.1
  url_launcher: ^6.3.2
  flutter_contacts: ^1.1.9+2
  http_parser: ^4.1.2
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  firebase_database: ^12.1.2
  flutter_local_notifications: ^20.0.0
  timeago: ^3.7.1
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.1
  firebase_auth: ^6.1.4
  pinput: ^5.0.0
  local_auth: ^3.0.0
  connectivity_plus: ^7.0.0
  flutter_dotenv: ^6.0.0
  googleapis: ^16.0.0
  record: ^6.2.0
  camera: ^0.11.3
  googleapis_auth: ^2.0.0
  # permission_handler: ^11.3.1
  audioplayers: ^6.5.1
  tflite_flutter: ^0.11.0
  flutter_foreground_task: ^6.1.2
  scidart: ^0.0.2-dev.12



dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  record_linux: ^1.0.0
  record_platform_interface: ^1.2.0
  tflite_flutter: ^0.11.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/tflite/help_raw_model.tflite


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter_18pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter_18pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter_18pt-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter_18pt-BoldItalic.ttf
          weight: 700
          style: italic
